import { describe, expect, it } from "vitest";
import {
  buildDiaryExistingTagsCatalog,
  evaluateDiaryGenerationGate,
  normalizeDiaryTags,
  normalizeGeneratedDiaryEntries,
  refineDiaryTagsForRetrieval,
} from "./diary";

describe("diary gate", () => {
  it("blocks when feature disabled", () => {
    const result = evaluateDiaryGenerationGate({
      enabled: false,
      nowMs: 10_000,
      lastActivityAtMs: 0,
      hasNewSource: true,
      newMessageCount: 10,
      newCharCount: 500,
    });
    expect(result).toEqual({ eligible: false, reason: "disabled" });
  });

  it("requires idle and interval and enough content", () => {
    const nowMs = 1_000_000;
    const result = evaluateDiaryGenerationGate({
      enabled: true,
      nowMs,
      lastActivityAtMs: nowMs - 11 * 60 * 1000,
      lastCheckedAtMs: nowMs - 16 * 60 * 1000,
      lastGeneratedAtMs: nowMs - 16 * 60 * 1000,
      hasNewSource: true,
      newMessageCount: 5,
      newCharCount: 300,
    });
    expect(result).toEqual({ eligible: true, reason: "ok" });
  });

  it("blocks when interval has not elapsed", () => {
    const nowMs = 2_000_000;
    const result = evaluateDiaryGenerationGate({
      enabled: true,
      nowMs,
      lastActivityAtMs: nowMs - 11 * 60 * 1000,
      lastCheckedAtMs: nowMs - 3 * 60 * 1000,
      hasNewSource: true,
      newMessageCount: 10,
      newCharCount: 800,
    });
    expect(result).toEqual({
      eligible: false,
      reason: "check_interval_not_elapsed",
    });
  });
});

describe("normalizeDiaryTags", () => {
  it("keeps model tags as-is (except empty and duplicates)", () => {
    const tags = normalizeDiaryTags([
      "topic:conflict about vacation",
      "emotion:frustrated",
      "abstract:maybe",
      "date:2026-04-20",
      "topic:conflict about vacation",
      "   ",
    ]);
    expect(tags).toEqual([
      "topic:conflict about vacation",
      "emotion:frustrated",
      "abstract:maybe",
      "date:2026-04-20",
    ]);
  });
});

describe("refineDiaryTagsForRetrieval", () => {
  it("does not post-filter generated tags", () => {
    const tags = refineDiaryTagsForRetrieval(
      normalizeDiaryTags([
        "date:2026-04-21",
        "topic:отношения",
        "emotion:уязвимость",
        "topic:обсуждение красного платья",
        "decision:показать фото в красном платье",
        "person:Илья",
        "followup:вернуться к теме встречи в пятницу",
      ]),
    );

    expect(tags).toEqual([
      "date:2026-04-21",
      "topic:отношения",
      "emotion:уязвимость",
      "topic:обсуждение красного платья",
      "decision:показать фото в красном платье",
      "person:Илья",
      "followup:вернуться к теме встречи в пятницу",
    ]);
  });
});

describe("normalizeGeneratedDiaryEntries", () => {
  it("keeps only non-empty entries with 1-3 non-date tags and prepends date tag", () => {
    const entries = normalizeGeneratedDiaryEntries(
      [
        {
          markdown: "  ### Разговор\nБыло тепло  ",
          tags: ["topic:разговор о встрече", "emotion:уязвимость", "date:2026-04-22"],
        },
        {
          markdown: "  ",
          tags: ["topic:пусто"],
        },
        {
          markdown: "### Без тегов",
          tags: ["date:2026-04-22"],
        },
        {
          markdown: "### Много тегов",
          tags: [
            "topic:тег 1",
            "topic:тег 2",
            "topic:тег 3",
            "topic:тег 4",
          ],
        },
      ],
      "date:2026-04-23",
    );

    expect(entries).toEqual([
      {
        markdown: "### Разговор\nБыло тепло",
        tags: ["date:2026-04-23", "topic:разговор о встрече", "emotion:уязвимость"],
      },
      {
        markdown: "### Много тегов",
        tags: ["date:2026-04-23", "topic:тег 1", "topic:тег 2", "topic:тег 3"],
      },
    ]);
  });

  it("applies safety cap for generated entries", () => {
    const entries = normalizeGeneratedDiaryEntries(
      [
        { markdown: "a", tags: ["topic:1"] },
        { markdown: "b", tags: ["topic:2"] },
        { markdown: "c", tags: ["topic:3"] },
      ],
      "date:2026-04-23",
      2,
    );

    expect(entries).toHaveLength(2);
  });
});

describe("buildDiaryExistingTagsCatalog", () => {
  it("returns top tags by frequency + recency and excludes date tags", () => {
    const catalog = buildDiaryExistingTagsCatalog(
      [
        {
          id: "d1",
          chatId: "chat-1",
          personaId: "persona-1",
          markdown: "x",
          tags: ["date:2026-04-21", "topic:встреча", "person:Илья"],
          sourceRange: { messageCount: 2 },
          autoGenerated: true,
          createdAt: "2026-04-21T10:00:00.000Z",
          updatedAt: "2026-04-21T10:00:00.000Z",
        },
        {
          id: "d2",
          chatId: "chat-1",
          personaId: "persona-1",
          markdown: "y",
          tags: ["date:2026-04-22", "topic:встреча", "emotion:тревога"],
          sourceRange: { messageCount: 3 },
          autoGenerated: true,
          createdAt: "2026-04-22T10:00:00.000Z",
          updatedAt: "2026-04-22T10:00:00.000Z",
        },
        {
          id: "d3",
          chatId: "chat-1",
          personaId: "persona-1",
          markdown: "z",
          tags: ["date:2026-04-23", "topic:платье", "emotion:радость"],
          sourceRange: { messageCount: 3 },
          autoGenerated: true,
          createdAt: "2026-04-23T10:00:00.000Z",
          updatedAt: "2026-04-23T10:00:00.000Z",
        },
      ],
      Date.parse("2026-04-23T12:00:00.000Z"),
      3,
    );

    expect(catalog).toEqual([
      "topic:встреча",
      "emotion:радость",
      "topic:платье",
    ]);
  });
});
